### ISSUE TITLE
Fails on "strange" characters

### ISSUE THREAD

**Issue by thedumbtechguy** [OnroerendErfgoed/Lukas#8]
Simple characters like `'` and `+` trip the parser.

**Comment by thedumbtechguy** [comment]
Is there anyway to make it simply ignore and remove the illegal characters?

**Comment by koenedaele** [comment]
Hi. I actually think it's a project we've kind of left behind. We never used this library in production. And we've moved all our newer stuff to python. So, I don't think we'll be continuing work on this.

**Comment by thedumbtechguy** [comment]
Thanks. I simply removed all non alphanumeric, _,  -, ( and ) 

Thanks

**Comment by koenedaele** [comment]
Are you planning on using this libray? As far as I know, you might be the only user for it.

**Comment by thedumbtechguy** [comment]
Yes I am. Actually using it with elasticsearch. Might build on it when i get the time to understand it.
